name: BPB Panel Obfuscation Pipeline

on: 
  push: { branches: [main] }
  schedule: [{ cron: "0 1 * * *" }]

permissions: 
  contents: write

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: { node-version: '20.x' }

    - name: Setup Environment
      run: |
        npm i -g javascript-obfuscator
        curl -sLo origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js‌:ml-citation{ref="1" data="citationList"}

    - name: Obfuscation Process
      run: |
        javascript-obfuscator origin.js -o _worker.js \
          --compact --control-flow-flattening --dead-code-injection \
          --identifier-names-generator hexadecimal --string-array-encoding rc4‌:ml-citation{ref="3,4" data="citationList"}

    - uses: stefanzweifel/git-auto-commit-action@v5
      with: 
        commit_message: ':robot: Auto-update obfuscated worker'
        branch: main
